package widget

import (
	"air_widget/internal/domain"
	"air_widget/internal/exam"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/gin-gonic/gin"
)

type widgetCodeExamMock struct {
	userID         uint32
	examKey        string
	expiresAt      int64
	neverExpires   bool
	allowedOrigins []string
	jti            string
	calls          int
}

func (m *widgetCodeExamMock) WidgetNewCode(userID uint32, examKey string, expiresAt int64, neverExpires bool, allowedOrigins []string, jti string) (string, error) {
	m.userID = userID
	m.examKey = examKey
	m.expiresAt = expiresAt
	m.neverExpires = neverExpires
	m.allowedOrigins = append([]string(nil), allowedOrigins...)
	m.jti = jti
	m.calls++
	return "signed-widget-code", nil
}

func (m *widgetCodeExamMock) WidgetParseCode(string) (*exam.WidgetCodeData, error) { return nil, nil }
func (m *widgetCodeExamMock) ExamUser(exam.Req) (string, error)                    { return "", nil }
func (m *widgetCodeExamMock) ParseToken(string) (*exam.Token, error)               { return nil, nil }
func (m *widgetCodeExamMock) UpdateToken(*exam.Token) (string, error)              { return "", nil }
func (m *widgetCodeExamMock) ParseExpiredToken(string) (*exam.Token, error)        { return nil, nil }
func (m *widgetCodeExamMock) VerifyToken() (bool, error)                           { return true, nil }
func (m *widgetCodeExamMock) CheckUserSubscription(uint32) error                   { return nil }

func TestHandleWidgetCodeGeneratesServerSideExamKey(t *testing.T) {
	gin.SetMode(gin.TestMode)

	mock := &widgetCodeExamMock{}
	u := &User{web: &Web{exam: mock}}
	router := gin.New()
	router.POST("/v1/widget/code", func(c *gin.Context) {
		c.Set("uid", uint32(23))
		u.handleWidgetCode(c)
	})

	req := httptest.NewRequest(http.MethodPost, "/v1/widget/code", strings.NewReader(`{
		"allowedUrls": ["https://localhost"],
		"neverExpires": true
	}`))
	req.Header.Set("Content-Type", "application/json")
	resp := httptest.NewRecorder()
	router.ServeHTTP(resp, req)

	if resp.Code != http.StatusOK {
		t.Fatalf("expected status 200, got %d: %s", resp.Code, resp.Body.String())
	}
	if mock.calls != 1 {
		t.Fatalf("expected one WidgetNewCode call, got %d", mock.calls)
	}
	if mock.userID != 23 {
		t.Fatalf("expected userID 23, got %d", mock.userID)
	}
	if mock.examKey == "" {
		t.Fatal("expected examKey to be generated by backend")
	}
	if len(mock.examKey) < 40 {
		t.Fatalf("expected a cryptographically sized examKey, got length %d", len(mock.examKey))
	}
	if mock.jti == "" {
		t.Fatal("expected jti to be generated by backend")
	}
	if mock.expiresAt != 0 || !mock.neverExpires {
		t.Fatalf("unexpected expiration settings: expiresAt=%d neverExpires=%v", mock.expiresAt, mock.neverExpires)
	}
	if len(mock.allowedOrigins) != 1 || mock.allowedOrigins[0] != "https://localhost" {
		t.Fatalf("unexpected allowed origins: %#v", mock.allowedOrigins)
	}
}

func TestGenerateWidgetCodeUsesFiniteExpiration(t *testing.T) {
	mock := &widgetCodeExamMock{}
	u := &User{web: &Web{exam: mock}}
	expiresAt := time.Now().Add(time.Hour).UTC()

	code, err := u.generateWidgetCode(23, domain.WidgetConfig{
		AllowedUrls:  []string{"https://localhost"},
		ExpiresAt:    &expiresAt,
		NeverExpires: false,
	})
	if err != nil {
		t.Fatal(err)
	}
	if code != "signed-widget-code" {
		t.Fatalf("unexpected widget code: %q", code)
	}
	if mock.expiresAt != expiresAt.Unix() {
		t.Fatalf("expected expiresAt %d, got %d", expiresAt.Unix(), mock.expiresAt)
	}
	if mock.neverExpires {
		t.Fatal("expected finite expiration")
	}
}
